// maincategory

export const ADD_MIANCATEGORY = "ADD_MAINCATEGORY"
export const ADD_MIANCATEGORY_RED = "ADD_MAINCATEGORY_RED"
export const GET_MIANCATEGORY = "GET_MAINCATEGORY"
export const GET_MIANCATEGORY_RED = "GET_MAINCATEGORY_RED"
export const UPDATE_MIANCATEGORY = "UPDATE_MAINCATEGORY"
export const UPDATE_MIANCATEGORY_RED = "UPDATE_MAINCATEGORY_RED"
export const DELETE_MIANCATEGORY = "DELETE_MAINCATEGORY"
export const DELETE_MIANCATEGORY_RED = "DELETE_MAINCATEGORY_RED"